### ISSUE TITLE
rest-tools testall reports parse error

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1120]
The `testall` function in the `zeppelin-rest-tools.sh` toolkit reports parse errors.

```
source /deployments/zeppelin/bin/zeppelin-rest-tools.sh

testall \
    "${username:?}" \
    "${password:?}" \
| tee "/tmp/${username}-testall.json" \
| jq '.'

```

Generates three error messages at the start of the run.
```
parse error: Invalid numeric literal at line 1, column 83
parse error: Invalid numeric literal at line 1, column 83
parse error: Invalid numeric literal at line 1, column 83
....
....
```

Deployment details:
```
aglais:
  status:
    deployment:
      type: hadoop-yarn
      conf: zeppelin-54.86-spark-6.26.43
      name: iris-gaia-blue-20230209
      date: 20230209T120757
      hostname: zeppelin.gaia-dmp.uk
  spec:
    openstack:
      cloud:
        base: arcus
        name: iris-gaia-blue

```
